Add embed texts pre-sorting
cohere-ai/cohere-python pull request #113
Opened 2022-10-28 14:52 UTC by vshmyhlo

2022-10-28 14:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cohere-ai/cohere-python?pullRequest=113) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cohere-ai/cohere-python?pullRequest=113) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cohere-ai/cohere-python?pullRequest=113) it.</sub>

2022-10-28 20:16 UTC, CoderHam requested changes

2022-10-28 20:16 UTC, CoderHam commented on cohere/utils.py
> +    for i, v in values_with_indices:
```suggestion
    indices_sorted = [x[0] for x in values_with_indices]
    values_sorted = [x[1] for x in values_with_indices]
```

2022-10-28 20:16 UTC, CoderHam commented on cohere/utils.py
> +    for _, v in values_with_indices:
```suggestion
    values_reordered = [x[1] for x in values_with_indices]
```

2023-03-14 17:18 UTC, sanderland commented
Closing due to major changes and old PR, please re-open based on main if still relevant.

2023-03-14 17:18 UTC, closed without merging