Chat - Deprecation warning chatlog override
cohere-ai/cohere-python pull request #226
Opened 2023-05-15 15:44 UTC by lusmoura

- Remove support for `chatlog_override`
- Remove tests
- This pull request will only be merged once all product owners who utilize this parameter have confirmed that they have made the necessary updates ([here](https://cohereai.slack.com/archives/C04J5P41JSD/p1684149549991589)).

2023-05-16 08:22 UTC, sanderland commented on cohere/client.py
> +                speaker = entry["speaker"].capitalize()
is this optional?
also capitalize() != upper() as suggested by docstring

2023-05-16 08:23 UTC, sanderland commented on cohere/client.py
> +            formatted_chat_history.append({"user_name": speaker, "text": text})
should this be "speaker": speaker ?

2023-05-16 08:23 UTC, sanderland commented on cohere/client.py
>      def _validate_chatlog_override(self, chatlog_override: List[Dict[str, str]]) -> None:
remove?

2023-05-16 08:24 UTC, sanderland commented on tests/sync/test_chat.py
> +                {"speaker": "CHATBOT", "text": "Hey! How can I help you?"},
please test capitalization logic

2023-05-16 08:24 UTC, sanderland commented on cohere/client.py
>              self._validate_chat_history(chat_history)
I think validation checks can be combined with format

2023-05-16 08:25 UTC, sanderland requested changes
some suggestions and fixes

2023-05-16 16:06 UTC, lusmoura commented
> some suggestions and fixes

@sanderland all the suggestions/fixes were related to the chat_history part of the PR, and after some discussion, we decided to postpone these changes. So I'll remove them an re-request the review.

2023-05-16 16:22 UTC, sanderland approved these changes

2023-05-17 13:41 UTC, BeatrixCohere approved these changes

2023-05-17 13:59 UTC, BeatrixCohere approved these changes

2023-05-17 14:34 UTC, merged