Remove unused chat parameters in Client and AsyncClient classes
cohere-ai/cohere-python pull request #400
Opened 2024-03-13 11:29 UTC by abdullahkady

Had a wrong base, reverted the commit.

2024-03-13 15:38 UTC, abdullahkady commented on CHANGELOG.md
> +## 4.55
you're right, but I didn't see a semver convention in place .. realistically breaking changes should change the major version (so 5.0), which I don't think we are allowed to do (5 exists as alpha already)

2024-03-14 13:42 UTC, sanderland approved these changes

2024-03-14 13:43 UTC, sanderland requested changes
Needs version in pyproject.toml

2024-03-14 14:23 UTC, sanderland approved these changes

2024-03-14 14:26 UTC, merged